### ISSUE TITLE
HySyntaxError on import using Hy v0.16 on latest Pypi release

### ISSUE THREAD

**Issue by MonsieurV** [hylang/hydiomatic#17]
When using the latest `hydiomatic` release with Hy v0.16.0, I got the following error:

```sh
hydiomatic.hy -h
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "/home/yoan/.local/bin/hydiomatic.hy", line 3
    [argparse]
    ^
hy.errors.HySyntaxError: parse error for special form 'import': should have reached end of form: HyList([
  HySymbol('argparse')])
```

Following the Hy CHANGELOG, [release 15](https://github.com/hylang/hy/releases/tag/0.15.0), that states:
> `(import [foo])` is no longer allowed. Use `(import foo)` instead.

Which seems to have been fixed in f7e56e2810f5331b207680260de64ea290314b9d

Could it be possible to make a new Pypi release including the fixes?

**Comment by brandonwillard** [comment]
Try it out now; tell me how it goes.

**Comment by MonsieurV** [comment]
Working fine :ok_man: Thanks man
